# Generated by Django 2.2.15 on 2020-09-02 21:13

import django.db.models.deletion
from django.db import migrations, models

import django_jsonfield_backport.models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ("scaife_viewer_atlas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextAlignmentRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("citation", models.CharField(max_length=13)),
                (
                    "items",
                    django_jsonfield_backport.models.JSONField(
                        blank=True, default=list
                    ),
                ),
                ("idx", models.IntegerField(help_text="0-based index")),
            ],
        ),
        migrations.CreateModel(
            name="TextAlignmentRecordRelation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("citation", models.CharField(max_length=13)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations",
                        to="scaife_viewer_atlas.TextAlignmentRecord",
                    ),
                ),
                (
                    "tokens",
                    models.ManyToManyField(
                        related_name="alignment_record_relations",
                        to="scaife_viewer_atlas.Token",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scaife_viewer_atlas.Node",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="textalignment", name="version",),
        migrations.AddField(
            model_name="textalignment",
            name="versions",
            field=sortedm2m.fields.SortedManyToManyField(
                help_text=None,
                related_name="text_alignments",
                to="scaife_viewer_atlas.Node",
            ),
        ),
        migrations.DeleteModel(name="TextAlignmentChunk",),
        migrations.AddField(
            model_name="textalignmentrecord",
            name="alignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="text_alignment_records",
                to="scaife_viewer_atlas.TextAlignment",
            ),
        ),
    ]
