# Generated by Django 2.2.15 on 2020-09-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scaife_viewer_atlas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textannotation",
            name="kind",
            field=models.CharField(
                choices=[("scholia", "Scholia"), ("syntax-tree", "Syntax tree")],
                default="scholia",
                max_length=7,
            ),
        ),
    ]
