# Generated by Django 2.2.15 on 2020-09-10 15:46

from django.db import migrations, models

import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ("scaife_viewer_atlas", "0003_syntax_trees"),
    ]

    operations = [
        migrations.CreateModel(
            name="Repo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("sha", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "metadata",
                    django_jsonfield_backport.models.JSONField(
                        blank=True, default=dict
                    ),
                ),
                (
                    "urns",
                    models.ManyToManyField(
                        related_name="repos", to="scaife_viewer_atlas.Node"
                    ),
                ),
            ],
        ),
    ]
