# Generated by Django 2.2.17 on 2020-12-11 05:23

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ("scaife_viewer_atlas", "0003_syntax_trees"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dictionary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "urn",
                    models.CharField(
                        help_text="urn:cite2:<site>:dictionaries.atlas_v1",
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DictionaryEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headword", models.CharField(max_length=255)),
                ("idx", models.IntegerField(help_text="0-based index")),
                (
                    "urn",
                    models.CharField(
                        help_text="urn:cite2:<site>:entries.atlas_v1",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "dictionary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="scaife_viewer_atlas.Dictionary",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sense",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                ("definition", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "idx",
                    models.IntegerField(
                        blank=True, help_text="0-based index", null=True
                    ),
                ),
                (
                    "urn",
                    models.CharField(
                        help_text="urn:cite2:<site>:senses.atlas_v1",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "citations",
                    sortedm2m.fields.SortedManyToManyField(
                        help_text=None,
                        related_name="senses",
                        to="scaife_viewer_atlas.Node",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="senses",
                        to="scaife_viewer_atlas.DictionaryEntry",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
