# Generated by Django 2.2.16 on 2020-10-21 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scaife_viewer_atlas", "0004_repo"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttributionOrganization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AttributionPerson",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("orcid_id", models.URLField(blank=True, max_length=36, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AttributionRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=255)),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scaife_viewer_atlas.AttributionOrganization",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scaife_viewer_atlas.AttributionPerson",
                    ),
                ),
                (
                    "urns",
                    models.ManyToManyField(
                        related_name="attribution_records",
                        to="scaife_viewer_atlas.Node",
                    ),
                ),
            ],
        ),
    ]
