# Generated by Django 2.2.17 on 2021-02-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scaife_viewer_atlas", "0004_citation_dictionary_dictionaryentry_sense"),
    ]

    operations = [
        migrations.AddField(
            model_name="dictionaryentry",
            name="headword_normalized",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
