# Generated by Django 2.2.17 on 2021-02-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scaife_viewer_atlas", "0004_repo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textannotation",
            name="kind",
            field=models.CharField(
                choices=[
                    ("scholia", "Scholia"),
                    ("syntax-tree", "Syntax tree"),
                    ("concordance-entry", "Concordance entry"),
                ],
                default="scholia",
                max_length=18,
            ),
        ),
    ]
