# Generated by Django 2.2.16 on 2021-05-18 15:39

from django.db import migrations, models
from scaife_viewer.atlas.hooks import hookset


class Migration(migrations.Migration):

    dependencies = [
        ("scaife_viewer_atlas", "0006_dictionary_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textannotation",
            name="kind",
            field=models.CharField(
                choices=hookset.TEXT_ANNOTATION_KIND_CHOICES,
                default=hookset.TEXT_ANNOTATION_DEFAULT_KIND,
                max_length=255,
            ),
        ),
    ]
