# Generated by Django 2.2.17 on 2021-03-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scaife_viewer_atlas", "0006_dictionary_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metadata",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idx",
                    models.IntegerField(
                        blank=True, help_text="0-based index", null=True
                    ),
                ),
                (
                    "urn",
                    models.CharField(
                        help_text="urn:cite2:<site>:metadata.atlas_v1",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "collection_urn",
                    models.CharField(
                        help_text="urn:cite2:<site>:metadata_collection.atlas_v1",
                        max_length=255,
                    ),
                ),
                (
                    "datatype",
                    models.CharField(
                        choices=[
                            ("str", "String"),
                            ("int", "Integer"),
                            ("date", "Date"),
                        ],
                        default="str",
                        max_length=4,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("value", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "index",
                    models.BooleanField(
                        default=True, help_text="Include in search index"
                    ),
                ),
            ],
        ),
    ]
