# Generated by Django 2.2.16 on 2021-05-25 17:32

from django.db import migrations, models
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ("scaife_viewer_atlas", "0007_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="metadata",
            name="value_obj",
            field=django_jsonfield_backport.models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="datatype",
            field=models.CharField(
                choices=[
                    ("str", "String"),
                    ("int", "Integer"),
                    ("date", "Date"),
                    ("obj", "Object"),
                ],
                default="str",
                max_length=4,
            ),
        ),
    ]
