# Generated by Django 2.2.17 on 2021-03-16 05:17

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ("scaife_viewer_atlas", "0007_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="metadata",
            name="cts_relations",
            field=sortedm2m.fields.SortedManyToManyField(
                help_text=None,
                related_name="structured_metadata",
                to="scaife_viewer_atlas.Node",
            ),
        ),
    ]
