# Generated by Django 2.2.17 on 2021-10-04 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scaife_viewer_atlas", "0008_named_entity_collection"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextAnnotationCollection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict
                    ),
                ),
                (
                    "urn",
                    models.CharField(
                        help_text="urn:cite2:<site>:text_annotation_collection.atlas_v1",
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="textannotation",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to="scaife_viewer_atlas.TextAnnotationCollection",
            ),
        ),
    ]
