# Generated by Django 2.2.26 on 2023-02-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scaife_viewer_atlas", "0013_grammaticalentry_grammaticalentrycollection"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageroi",
            name="tokens",
            field=models.ManyToManyField(
                related_name="roi", to="scaife_viewer_atlas.Token"
            ),
        ),
    ]
