# Generated by Django 2.2.26 on 2023-04-06 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scaife_viewer_atlas", "0008_metadata"),
        ("scaife_viewer_atlas", "0013_grammaticalentry_grammaticalentrycollection"),
    ]

    operations = []
