# Generated by Django 2.2.26 on 2023-02-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scaife_viewer_atlas", "0014_imageroi_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageroi",
            name="urn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
