# Generated by Django 2.2.26 on 2023-07-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scaife_viewer_atlas", "0014_merge_20230406_1139"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="space_after",
            field=models.BooleanField(default=True),
        ),
    ]
