# Generated by Django 2.2.26 on 2023-10-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scaife_viewer_atlas", "0014_merge_20230406_1139"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageroi",
            name="urn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
