# Generated by Django 2.2.26 on 2023-10-24 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scaife_viewer_atlas", "0015_imageroi_urn"),
        ("scaife_viewer_atlas", "0015_token_space_after"),
    ]

    operations = []
