# Generated by Django 2.2.26 on 2023-12-28 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scaife_viewer_atlas", "0015_tocentry"),
        ("scaife_viewer_atlas", "0015_imageroi_urn"),
    ]

    operations = []
