# Generated by Django 2.2.26 on 2023-12-28 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scaife_viewer_atlas', '0016_merge_20231024_0512'),
        ('scaife_viewer_atlas', '0015_tocentry'),
    ]

    operations = [
    ]
